@protocol= http
@domainname= localhost
@port= {{$dotenv PORT}}
@path=v1
@baseUrl = {{protocol}}://{{domainname}}:{{port}}/{{path}}

###
GET {{baseUrl}}

### 

###
GET {{baseUrl}}/author
Authentication: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImplYW52YWxqZWFuamVhbiIsImlhdCI6MTYxNTIxOTc5MX0.CawG4o_fVj6FQ-iV9Jdj1ri9LTi43LHyfLI2jL9TrtI


### 

POST {{baseUrl}}/signup
Content-Type: application/json

{
   "username" : "jeanmarie",
   "email" : "bgdsfdfsdfsu93@mail.fr",
   "password" : "jenesuispasencorehaché",
   "city" : "bordeaux"
} 
###

POST {{baseUrl}}/login
Content-Type: application/json

{
   "email" : "bgdu79@mail.fr",
   "password" : "jenesuispasencorehaché"
} 
###

POST http://ec2-54-145-80-6.compute-1.amazonaws.com/v1/signup
Content-Type: application/json

{
    "username": "jeaneustache",
    "email": "bgdu99@mail.fr",
    "password": "jenesuispasencorehaché",
    "city": "bordeaux"
}
###

POST http://ec2-54-145-80-6.compute-1.amazonaws.com/v1/login
Content-Type: application/json

{
   "email" : "bgdu99@mail.fr",
   "password" : "jenesuispasencorehaché"
} 
###
GET http://ec2-54-145-80-6.compute-1.amazonaws.com/v1/author
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImplYW5ldXN0YWNoZSIsImlhdCI6MTYxNTIyMDA1N30.E9w8mPhJnLm0FST_qsK8r68JK6rHzVRVrydwwQ5j1UI

### 