@protocol= http
@domainname= localhost
@port= {{$dotenv PORT}}
@path=v1
@baseUrl = {{protocol}}://{{domainname}}:{{port}}/{{path}}

###
GET {{baseUrl}}/

### 

POST {{baseUrl}}/signup
Content-Type: application/json

{
   "username" : "jeanvaljeanjean",
   "email" : "bgdu79@mail.fr",
   "password" : "jenesuispasencorehaché",
   "city" : "bordeaux"
} 