name: Front - push on dev

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '15.x'
    - name: Install npm dependencies
      working-directory: ./apps/back
      run: npm install
    - name: Check the lint
      working-directory: ./apps/back
      run: npm run lint
        
  deploy:
    needs: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '15.x'
    - name: Install npm dependencies
      working-directory: ./apps/back
      run: npm install
    - name: Copy the env
      working-directory: ./apps/back
      run: cp .env.dist .env
    - uses: cschleiden/replace-tokens@v1
      with:
        files: '.env'
      env:
        PG_URL: ${{ secrets.INT_BACK_PG_URL }}
        ACCESS_TOKEN_SECRET: ${{ secrets.INT_BACK_ACCESS_TOKEN_SECRET }}
        PATH_PICTURE: ${{ secrets.INT_BACK_PATH_PICTURE }}
        PORT: ${{ secrets.INT_BACK_PORT }}
    - name: Deploy to Staging server
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
        SSH_PRIVATE_KEY: ${{ secrets.INT_SSH_PRIVATE_KEY }}
        ARGS: "-avzr --delete"
        SOURCE: apps/back/*
        REMOTE_HOST: ${{ secrets.INT_REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.INT_REMOTE_USER }}
        TARGET: ${{ secrets.INT_REMOTE_BACK_TARGET }}