name: Front - push on dev

on:
  push:
    branches:
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '15.x'
    - name: Install npm dependencies
      working-directory: ./apps/front
      run: npm install
    - name: Check the lint
      working-directory: ./apps/front
      run: npm run lint

  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '15.x'
    - name: Install npm dependencies
      working-directory: ./apps/front
      run: npm install
    - name: Copy the env
      working-directory: ./apps/front
      run: cp .env.dist .env
    - uses: cschleiden/replace-tokens@v1
      with:
        files: './apps/front/.env'
      env:
        API_URL: ${{ secrets.INT_FRONT_API_URL }}
    - name: Run build task
      working-directory: ./apps/front
      run: npm run build
    - name: Create front artifact
      uses: actions/upload-artifact@v2
      with:
        name: front-build ${{ matrix.node-version }}
        path: ${{ github.workspace }}/apps/front/dist
        
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Dowload front artifact
      uses: actions/download-artifact@v2
      with:
        name: front-build ${{ matrix.node-version }}
        path: ${{ github.workspace }}/apps/front/dist
    - name: Deploy to Staging server
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
        SSH_PRIVATE_KEY: ${{ secrets.INT_SSH_PRIVATE_KEY }}
        ARGS: "-avzr --delete"
        SOURCE: apps/front/dist/*
        REMOTE_HOST: ${{ secrets.INT_REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.INT_REMOTE_USER }}
        TARGET: ${{ secrets.INT_REMOTE_FRONT_TARGET }}